--------------------------------------------------------
--  File created - Wednesday-July-10-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QB_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "DLH_BAJAJK"."QB_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER(3,0), 
	"CATEGORY_NAME" VARCHAR2(255 BYTE), 
	"ADDED_BY" VARCHAR2(255 BYTE), 
	"MARK_TO_DELETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_TEMP" ;
--------------------------------------------------------
--  DDL for Index QB_CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLH_BAJAJK"."QB_CATEGORIES_PK" ON "DLH_BAJAJK"."QB_CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_TEMP" ;
--------------------------------------------------------
--  Constraints for Table QB_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "DLH_BAJAJK"."QB_CATEGORIES" ADD CONSTRAINT "QB_CATEGORIES_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_TEMP"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QB_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "DLH_BAJAJK"."QB_CATEGORIES" ADD CONSTRAINT "QB_CATEGORIES_FK1" FOREIGN KEY ("ADDED_BY")
	  REFERENCES "DLH_BAJAJK"."QB_USER_PROFILES" ("USERNAME") ENABLE;
